### ISSUE TITLE
0.5.0 appears to break for multiline cmake commands

### ISSUE THREAD

**Issue by emkornfield** [cheshirekow/cmake_format#107]
cmake_format 0.5.0 fails on our CMake file (0.4.5 worked).

Original file: https://github.com/apache/arrow/blob/master/cpp/CMakeLists.txt

Error message (https://travis-ci.org/apache/arrow/jobs/526099112):
```
While processing /home/travis/build/apache/arrow/cpp/CMakeLists.txt
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/cmake-format", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/__main__.py", line 439, in main
    process_file(cfg, infile, outfile, args.dump)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/__main__.py", line 113, in process_file
    parse_tree = parser.parse(tokens, parse_db)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/parser.py", line 1061, in parse
    return consume_body(tokens, parse_db)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/parser.py", line 1034, in consume_body
    subtree = consume_flowcontrol(tokens, parse_db)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/parser.py", line 988, in consume_flowcontrol
    return consume_ifblock(tokens, parse_db)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/parser.py", line 969, in consume_ifblock
    body = consume_body(tokens, parse_db, breakset)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/cmake_format/parser.py", line 1044, in consume_body
    tokens[0].begin.line, tokens[0].begin.col))
AssertionError: Unexpected UNQUOTED_LITERAL token at 701:20
```

What appears to be the relevant segment:
```
 add_custom_target(cscope find ${CMAKE_CURRENT_SOURCE_DIR}
                    (-name
                     \\*.cc
                     -or 
                     -name
                     \\*.hh
                     -or 
                     -name
                     \\*.cpp
                     -or 
                     -name
                     \\*.h
                     -or 
                     -name
                     \\*.c
                     -or 
                     -name
                     \\*.f)
                    -exec
                    echo
                    \"{}\"
                    \;  
                    >   
                    cscope.files
                    &&  
                    cscope
                    -q
                    -b
                    VERBATIM)
```

**Comment by cheshirekow** [comment]
I don't think it's the multiline... I think it's the presence of the parenthesis. Based on my understanding of [the cmake language][1] I don't think that is legal as an unquoted element. Perhaps cmake is more generous than it's language specification would imply... or I'm misunderstanding the language specification. As a work-around, try quoting the argument. 

I will look into this though.

**Comment by emkornfield** [comment]
Looks like you might be right.  looking into fixing our CMake files.

**Comment by cheshirekow** [comment]
FYI I think this should be fixed in the next incremental release. If you'd like to test you can try [this temporary branch][1]: `hotfixes_0.5.0`

[1]: https://github.com/cheshirekow/cmake_format/tree/hotfixes_0.5.0

**Comment by emkornfield** [comment]
Belated Thank you, it looks like it has.
