### ISSUE TITLE
Formatting of Nested Expressions Fails

### ISSUE THREAD

**Issue by sanssecours** [cheshirekow/cmake_format#110]
# Steps to Reproduce

1. Create a file `test.cmake` with the following content:

   ```cmake
   if(NOT ("" STREQUALS ""))
   endif()
   ```

3. Run `cmake-format`:

   ```sh
   cmake-format test.cmake
   ```

# Expected Result

The command `cmake-format` prints a nicely formatted version of the given CMake code.

# Actual Result

The command fails with an `AssertionError`:

```
While processing test.cmake
Traceback (most recent call last):
  File "pyenv/versions/3.7.3/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format==0.5.1.dev1', 'console_scripts', 'cmake-format')()
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/__main__.py", line 439, in main
    process_file(cfg, infile, outfile, args.dump)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/__main__.py", line 113, in process_file
    parse_tree = parser.parse(tokens, parse_db)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/parser.py", line 1066, in parse
    return consume_body(tokens, parse_db)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/parser.py", line 1039, in consume_body
    subtree = consume_flowcontrol(tokens, parse_db)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/parser.py", line 993, in consume_flowcontrol
    return consume_ifblock(tokens, parse_db)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/parser.py", line 974, in consume_ifblock
    body = consume_body(tokens, parse_db, breakset)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev1-py3.7.egg/cmake_format/parser.py", line 1049, in consume_body
    tokens[0].begin.line, tokens[0].begin.col))
AssertionError: Unexpected RIGHT_PAREN token at 1:24
```

.

# System Information

- cmake format `0.5.1.dev1`
- macOS `10.14.4`

**Comment by cheshirekow** [comment]
Got it. I'm able to reproduct. I've updated the `hotfixes_0.5.0` branch [(link)][1] with a fix for this too.  

[1]: https://github.com/cheshirekow/cmake_format/tree/hotfixes_0.5.0

**Comment by sanssecours** [comment]
Thank you for the quick update. I think I found another similar problem that is not fixed in cmake format `0.5.1dev2`. Formatting the code:

```cmake
if (SOMETHING AND (NOT SOMETHING_ELSE STREQUAL ""))
endif (SOMETHING AND (NOT SOMETHING_ELSE STREQUAL ""))
```

produces another `AssertionError`:

```
While processing test.cmake
Traceback (most recent call last):
  File "pyenv/versions/3.7.3/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format==0.5.1.dev2', 'console_scripts', 'cmake-format')()
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev2-py3.7.egg/cmake_format/__main__.py", line 439, in main
    process_file(cfg, infile, outfile, args.dump)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev2-py3.7.egg/cmake_format/__main__.py", line 113, in process_file
    parse_tree = parser.parse(tokens, parse_db)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev2-py3.7.egg/cmake_format/parser.py", line 1076, in parse
    return consume_body(tokens, parse_db)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev2-py3.7.egg/cmake_format/parser.py", line 1059, in consume_body
    tokens[0].begin.line, tokens[0].begin.col))
AssertionError: Unexpected RIGHT_PAREN token at 2:53
```

.

**Comment by cheshirekow** [comment]
Updated the same branch with a fix.

**Comment by sanssecours** [comment]
Thank you for working on this. Unfortunately the latest version of `cmake-format` does not work on my machine.

# Steps to Reproduce the Problem

1. Download https://github.com/cheshirekow/cmake_format/archive/hotfixes_0.5.0.zip
2. Unpack the zip-file
3. Change into the root folder of the unpacked zip-file
4. Run the following command:

   ```sh
   python setup.py install
   ```

5. Run `cmake-format`

   ```sh
   cmake-format
   ```

# Expected Result

The command `cmake-format` exits successfully.

# Actual Result

The command fails, printing the following message:

```
Traceback (most recent call last):
  File "pyenv/versions/3.7.3/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format==0.5.1.dev4', 'console_scripts', 'cmake-format')()
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev4-py3.7.egg/cmake_format/__main__.py", line 35, in <module>
    from cmake_format import parse_funs
ImportError: cannot import name 'parse_funs' from 'cmake_format' (pyenv/versions/3.7.3/lib/python3.7/site-packages/cmake_format-0.5.1.dev4-py3.7.egg/cmake_format/__init__.py)
```

.

**Comment by cheshirekow** [comment]
Let me see if I can find a python 3.7 to test.

**Comment by cheshirekow** [comment]
Ok, got it. Forgot to add `cmake_format.parse_funs` to `setup.py`
