### ISSUE TITLE
(version 0.5.2) Crash in python "'NoneType' object has no attribute 'startswith'"

### ISSUE THREAD

**Issue by 1989wanghang** [cheshirekow/cmake_format#116]
Traceback (most recent call last):
  File "/home/wangh/.local/bin/cmake-format", line 10, in <module>
    sys.exit(main())
  File "/home/wangh/.local/lib/python3.5/site-packages/cmake_format/__main__.py", line 417, in main
    config_dict = get_config(infile_path, args.config_file)
  File "/home/wangh/.local/lib/python3.5/site-packages/cmake_format/__main__.py", line 212, in get_config
    configfile_path = os.path.expanduser(configfile_path)
  File "/usr/lib/python3.5/posixpath.py", line 228, in expanduser
    if not path.startswith(tilde):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by cheshirekow** [comment]
This is the same as #115. Fix in flight.
