### ISSUE TITLE
npm install err's due to eventstream 3.3.6

### ISSUE THREAD

**Issue by hugolm84** [cheshirekow/cmake_format#132]
Hi!

Trying to setup develop environment for vs code extension. While installing dependencies via `npm install`, the installation process errors and exits due to removed package dependency event-stream 3.3.6. That version is apparently considered malicious and have been removed. 

Some more information: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

Log:
```
3578 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
3578 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
3578 verbose stack     at runMicrotasks (<anonymous>)
3578 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
3579 verbose statusCode 404
3580 verbose pkgid event-stream@3.3.6
3581 verbose cwd /Users/hugo/Devel/cmake_format/cmake_format/vscode_extension
3582 verbose Darwin 17.7.0
3583 verbose argv "/usr/local/Cellar/node/12.10.0/bin/node" "/usr/local/bin/npm" "install"
3584 verbose node v12.10.0
3585 verbose npm  v6.11.3
3586 error code E404
3587 error 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
3588 error 404
3589 error 404 'event-stream@3.3.6' is not in the npm registry.
3590 error 404 You should bug the author to publish it (or use the name yourself!)
3591 error 404 It was specified as a dependency of 'vscode_extension'
3592 error 404 Note that you can also install from a
3593 error 404 tarball, folder, http url, or git url.
```

**Comment by cheshirekow** [comment]
I am unsurprised. `npm` is kind of a mess. Thanks for the report, I will push an updated package list.

**Comment by cheshirekow** [comment]
I can't reproduce this. I just ran `npm install` in a fresh checkout and this is what I see:
```
Detected VS Code engine version: ^1.23.0
Found minimal version that qualifies engine range: 1.23.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

added 269 packages from 507 contributors and audited 892 packages in 4.886s
found 7 vulnerabilities (2 low, 2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by hugolm84** [comment]
Would VS Code version matter?  I run August 2019 (version 1.38) with NPM 6.12.0-next.0

```
hugo at Hugos-MBP in ~/Devel/cmake_format/cmake_format/vscode_extension on master [?$]
$ npm install
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/.npmignore'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/map-stream-2b3c3ca4/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/browser.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/map-stream-2b3c3ca4/.npmignore'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/node.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/map-stream-2b3c3ca4/LICENCE'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/test.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/map-stream-2b3c3ca4/index.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/math-random-e46fa9f0/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/map-stream-2b3c3ca4/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/mime-db-60b523a0/HISTORY.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/form-data-bbc3dab2/lib/populate.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/configs/all.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/configs/all.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/configs/latest.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/configs/latest.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/configs/recommended.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/configs/recommended.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/checkstyleFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/typescript-5d1c172f/lib/it'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/checkstyleFormatter.js'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/typescript-5d1c172f/lib/ja'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/codeFrameFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/codeFrameFormatter.js'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/typescript-5d1c172f/lib/ko'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/fileslistFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/fileslistFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/typescript-5d1c172f/lib/lib.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/index.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/index.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/jsonFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/jsonFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/junitFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/diff-fe1e6068/dist/diff.min.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/junitFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/msbuildFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/msbuildFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/source-map-7b3e531f/dist/source-map.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/pmdFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/pmdFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/proseFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/proseFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/stylishFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/stylishFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/tapFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/tapFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/verboseFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/verboseFormatter.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/vsoFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/formatters/vsoFormatter.js'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/formatter'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/rule'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/typeUtils.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/typeUtils.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/utils.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/utils.js'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/language/walker'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/adjacentOverloadSignaturesRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/adjacentOverloadSignaturesRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/alignRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/alignRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/arrayTypeRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/arrayTypeRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/arrowParensRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/arrowParensRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/arrowReturnShorthandRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/arrowReturnShorthandRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/awaitPromiseRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/awaitPromiseRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/banCommaOperatorRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/banCommaOperatorRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/banRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/banRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/banTypesRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/banTypesRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/binaryExpressionOperandOrderRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/binaryExpressionOperandOrderRule.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/callableTypesRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/hugo/Devel/cmake_format/cmake_format/vscode_extension/node_modules/.staging/tslint-7d0f8b5e/lib/rules/callableTypesRule.js'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'vscode_extension'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hugo/.npm/_logs/2019-09-28T18_50_47_095Z-debug.log
```

**Comment by cheshirekow** [comment]
I don't think it should matter, I think npm/vsce are working outside of vscode. The npm or node version might matter. I've got `npm` version `6.4.1` which appears a bit older than the one you've got. Looking in a bit further the URL https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz does appear to be broken (yields `{"error":"Not found"}`). My guess is that there must be some cache somewhere on my machine that is allowing this to work?? Or maybe the treatment of package-lock is different between npm versions. 

Honestly I think I might remove `package-lock.json`. The whole purpose of it's existence is to *avoid* this kind of issue... which it clearly is not doing.

**Comment by hugolm84** [comment]
> Actually we don't need to update all the packages that depends on event-stream@3.3.6.
> 
> You can open the package-lock.json, remove all the event-stream references and call npm install again. It will be faster.

https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6

**Comment by cheshirekow** [comment]
Thanks @hugolm84. I've removed event-stream from `package-lock.json` and it seams that npm is happy so I'll push this soon.

**Comment by cheshirekow** [comment]
This is live. The next push also removes `flatmap-stream`... which was evidently the vulnerable package. I'm going to close this issue but feel free to continue any discussion and we can re-open it if there is more to be done.
