### ISSUE TITLE
Support bracket/block comments

### ISSUE THREAD

**Issue by iabenz** [cheshirekow/cmake_format#15]
Very cool project you've created!

Many of my CMake scripts begin with a multi-line comment of the form `#[[comment]]`. I get the following error when attempting to format this example [CMakeLists.txt](https://github.com/cheshirekow/cmake_format/files/1709192/CMakeLists.txt):
> Error while processing CMakeLists.txt
While processing CMakeLists.txt
Traceback (most recent call last):
  File "C:\Python27\Scripts\cmake-format-script.py", line 9, in <module>
    load_entry_point('cmake-format==0.3.0', 'console_scripts', 'cmake-format')()
  File "c:\python27\lib\site-packages\cmake_format\__main__.py", line 211, in main
    process_file(config, infile, outfile)
  File "c:\python27\lib\site-packages\cmake_format\__main__.py", line 35, in process_file
    tok_seqs = parser.digest_tokens(tokens)
  File "c:\python27\lib\site-packages\cmake_format\parser.py", line 145, in digest_tokens
    tokens[0].line, tokens[0].col))
AssertionError: Unexpected token of type UNQUOTED_LITERAL at 2:0

Would you consider adding support for this style of comment?

**Comment by cheshirekow** [comment]
Oh, wow, I didn't even know this was a thing. Note to self for later, here is the syntax for mult-line comments: https://cmake.org/cmake/help/v3.1/manual/cmake-language.7.html#comments
