### ISSUE TITLE
AssertionError on call of externalproject_add_stepdependencies

### ISSUE THREAD

**Issue by kumekay** [cheshirekow/cmake_format#152]
I've tryed to run formatter v0.6.2, 
And it exits with AssertionError on this line:
https://github.com/espressif/esp-idf/blob/master/tools/cmake/kconfig.cmake#L55

at the call to built-in CMake function `externalproject_add_stepdependencies`

Error message
```
[WARNING] __main__.py:514: While processing tools/cmake/kconfig.cmake
Traceback (most recent call last):
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/bin/cmake-format", line 8, in <module>
    sys.exit(main())
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/__main__.py", line 508, in main
    outtext = process_file(cfg, intext, args.dump, extra)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/__main__.py", line 125, in process_file
    box_tree = formatter.layout_tree(parse_tree, config)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1539, in layout_tree
    root_box.reflow(stack_context, Cursor(0, 0))
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1358, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1393, in _reflow
    stack_context, column_cursor + (0, config.tab_size), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1358, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1393, in _reflow
    stack_context, column_cursor + (0, config.tab_size), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1358, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1393, in _reflow
    stack_context, column_cursor + (0, config.tab_size), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1358, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1412, in _reflow
    (0, config.tab_size), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 1358, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 669, in reflow
    max(passno for passno, _ in self._layout_passes))
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 429, in reflow
    stack_context, cursor.clone(), passno)
  File "/Users/ku/.espressif/python_env/idf4.1_py3.7_env/lib/python3.7/site-packages/cmake_format/formatter.py", line 748, in _reflow
    .format(child.node_type, child.pnode))
AssertionError: Expected ARGGROUP node, but got NodeType.PARGGROUP at PARGGROUP: 55:53
```

Formatter config:
```
# --------------------------
# General Formatting Options
# --------------------------
# How wide to allow formatted cmake files
line_width = 120

# How many spaces to tab for indent
tab_size = 4

# If an argument group contains more than this many sub-groups (parg or kwarg
# groups), then force it to a vertical layout.
max_subgroups_hwrap = 3

# If a positional argument group contains more than this many arguments, then
# force it to a vertical layout.
max_pargs_hwrap = 6

# If true, separate flow control names from their parentheses with a space
separate_ctrl_name_with_space = False

# If true, separate function names from parentheses with a space
separate_fn_name_with_space = False

# If a statement is wrapped to more than one line, than dangle the closing
# parenthesis on it's own line.
dangle_parens = False

# If the trailing parenthesis must be 'dangled' on it's on line, then align it
# to this reference: `prefix`: the start of the statement,  `prefix-indent`: the
# start of the statement, plus one indentation  level, `child`: align to the
# column of the arguments
dangle_align = 'prefix'

min_prefix_chars = 4

# If the statement spelling length (including space and parenthesis) is larger
# than the tab width by more than this amount, then force reject un-nested
# layouts.
max_prefix_chars = 10

# If a candidate layout is wrapped horizontally but it exceeds this many lines,
# then reject the layout.
max_lines_hwrap = 2

# What style line endings to use in the output.
line_ending = 'unix'

# Format command names consistently as 'lower' or 'upper' case
command_case = 'canonical'

# Format keywords consistently as 'lower' or 'upper' case
keyword_case = 'unchanged'

# Specify structure for custom cmake functions
additional_commands = {
  "pkg_find": {
    "kwargs": {
      "PKG": "*"
    }
  }
}

# A list of command names which should always be wrapped
always_wrap = []

# If true, the argument lists which are known to be sortable will be sorted
# lexicographicall
enable_sort = True

# If true, the parsers may infer whether or not an argument list is sortable
# (without annotation).
autosort = False

# If a comment line starts with at least this many consecutive hash characters,
# then don't lstrip() them off. This allows for lazy hash rulers where the first
# hash char is not separated by space
hashruler_min_length = 10

# By default, if cmake-format cannot successfully fit everything into the
# desired linewidth it will apply the last, most agressive attempt that it made.
# If this flag is True, however, cmake-format will print error, exit with non-
# zero status code, and write-out nothing
require_valid_layout = False

# A dictionary containing any per-command configuration overrides. Currently
# only `command_case` is supported.
per_command = {}

# A dictionary mapping layout nodes to a list of wrap decisions. See the
# documentation for more information.
layout_passes = {}


# --------------------------
# Comment Formatting Options
# --------------------------
# What character to use for bulleted lists
bullet_char = '*'

# What character to use as punctuation after numerals in an enumerated list
enum_char = '.'

# enable comment markup parsing and reflow
enable_markup = False

# If comment markup is enabled, don't reflow the first comment block in each
# listfile. Use this to preserve formatting of your copyright/license
# statements.
first_comment_is_literal = False

# If comment markup is enabled, don't reflow any comment block which matches
# this (regex) pattern. Default is `None` (disabled).
literal_comment_pattern = None

# Regular expression to match preformat fences in comments
# default=r'^\s*([`~]{3}[`~]*)(.*)$'
fence_pattern = '^\\s*([`~]{3}[`~]*)(.*)$'

# Regular expression to match rulers in comments
# default=r'^\s*[^\w\s]{3}.*[^\w\s]{3}$'
ruler_pattern = '^\\s*[^\\w\\s]{3}.*[^\\w\\s]{3}$'

# If true, then insert a space between the first hash char and remaining hash
# chars in a hash ruler, and normalize it's length to fill the column
canonicalize_hashrulers = True


# ---------------------------------
# Miscellaneous Options
# ---------------------------------
# If true, emit the unicode byte-order mark (BOM) at the start of the file
emit_byteorder_mark = False

# Specify the encoding of the input file. Defaults to utf-8.
input_encoding = 'utf-8'

# Specify the encoding of the output file. Defaults to utf-8. Note that cmake
# only claims to support utf-8 so be careful when using anything else
output_encoding = 'utf-8'
```

**Comment by cheshirekow** [comment]
Confirmed, reproduced. I don't have test coverage on these and I think it broke during a recent parse refactor. The fix is this:

```
diff --git a/cmake_format/parse_funs/external_project.py b/cmake_format/parse_funs/external_project.py
index 9dc40b8..d8ad80e 100644
--- a/cmake_format/parse_funs/external_project.py
+++ b/cmake_format/parse_funs/external_project.py
@@ -155,5 +155,5 @@ def populate_db(parse_db):
   parse_db["externalproject_get_property"] = StandardParser('+')
   parse_db["externalproject_add_step"] = parse_external_project_add_step
   parse_db["externalproject_add_steptargets"] = \
-      PositionalParser('+', flags=["NO_DEPENDS"])
-  parse_db["externalproject_add_stepdependencies"] = PositionalParser('+')
+      StandardParser('+', flags=["NO_DEPENDS"])
+  parse_db["externalproject_add_stepdependencies"] = StandardParser('+')
```

And will be included in the next release.

**Comment by kumekay** [comment]
Thank you for extremely quick answer and whole project! Fix works just fine.
