### ISSUE TITLE
cmake-lint crash while process CMakeLists.txt

### ISSUE THREAD

**Issue by hellozee** [cheshirekow/cmake_format#169]
[Here](https://github.com/hellozee/lzr/blob/master/CMakeLists.txt) is the CMakeLists.txt

and the corresponding traceback
```
WARNING While processing CMakeLists.txt
Traceback (most recent call last):
  File "/home/hellozee/.local/bin/cmake-lint", line 11, in <module>
    sys.exit(main())
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/__main__.py", line 142, in main
    process_file(cfg, local_ctx, intext)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/__main__.py", line 43, in process_file
    basic_checker.check_parse_tree(config, local_ctx, parse_tree)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 565, in check_parse_tree
    check_tree(cfg, local_ctx, node)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 548, in check_tree
    check_body(cfg, local_ctx, node)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 358, in check_body
    check_tree(cfg, local_ctx, child)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 554, in check_tree
    check_statement(cfg, local_ctx, node)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 507, in check_statement
    check_tree(cfg, local_ctx, child)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 552, in check_tree
    check_arggroup(cfg, local_ctx, node)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 376, in check_arggroup
    check_tree(cfg, local_ctx, child)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 556, in check_tree
    check_positional_group(cfg, local_ctx, node)
  File "/home/hellozee/.local/lib/python3.6/site-packages/cmake_lint/basic_checker.py", line 381, in check_positional_group
    min_npargs = get_min_npargs(node.spec.npargs)
AttributeError: 'NoneType' object has no attribute 'npargs'
```

Am I doing something wrong?

**Comment by cheshirekow** [comment]
You're not doing anything wrong. `cmake-lint` is [super new][1] and doesn't have great test coverage. This is the same as #168 and I think is already fixed upstream. Please try again with the next release. 

[1]: https://github.com/cheshirekow/cmake_format/releases/tag/v0.6.3

**Comment by hellozee** [comment]
ohh good to know, thanks for working on it, :smile:

**Comment by cheshirekow** [comment]
This is done. Will be in the next release.
