### ISSUE TITLE
cmake-lint crashes on a statement in the function 

### ISSUE THREAD

**Issue by tomasbw** [cheshirekow/cmake_format#175]
function(func_name _param _list)
    if((NOT ${_param} STREQUAL "PARAM") AND (NOT ${_param} IN_LIST ${_list}))
        return()
    endif()
endfunction()

Traceback (most recent call last):
  File "/home/user/.local/bin/cmake-lint", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/cmake_lint/__main__.py", line 133, in main
    local_ctx.writeout(outfile)
  File "/home/user/.local/lib/python3.7/site-packages/cmake_lint/lint_util.py", line 81, in writeout
    for record in self.get_lint():
  File "/home/user/.local/lib/python3.7/site-packages/cmake_lint/lint_util.py", line 78, in get_lint
    record.location, record) for record in self._lint)]
TypeError: '<' not supported between instances of 'LintRecord' and 'LintRecord'

**Comment by cheshirekow** [comment]
That is bizarre. The records are sorted by `(record.location, record.spec.idstr, idx, record)`, so even if `location` and `idstr` are duplicates, `idx` should always be unique (and `record` itself should never be compared with less-than). 

I actually see this code [on line  84][1] not 78, so are you perhaps using an older version? 

[1]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_lint/lint_util.py#L84

**Comment by tomasbw** [comment]
Upgraded from 0.6.3 to 0.6.9 now it works. 
Thanks
