### ISSUE TITLE
AssertionError when using on CMakeLists.txt

### ISSUE THREAD

**Issue by kdheepak** [cheshirekow/cmake_format#2]
```bash
$ cmake-format CMakeLists.txt
Error while processing CMakeLists.txt
While processing CMakeLists.txt
Traceback (most recent call last):
  File "/Users/$USER/miniconda3/envs/python27/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format', 'console_scripts', 'cmake-format')()
  File "/Users/$USER/GitRepos/cmake_format/cmake_format/__main__.py", line 111, in main
    process_file(config, infile, outfile)
  File "/Users/$USER/GitRepos/cmake_format/cmake_format/__main__.py", line 26, in process_file
    fst = parser.construct_fst(tok_seqs)
  File "/Users/$USER/GitRepos/cmake_format/cmake_format/parser.py", line 365, in construct_fst
    assert block_stack and block_stack[-1].block_type == IF_BLOCK
AssertionError
```

**Comment by kdheepak** [comment]
This is the CMakeLists.txt file that we are using over [here](https://raw.githubusercontent.com/GMLC-TDC/HELICS-src/2f5ef6c7e70b27a9314e73fb39092364f38f87d2/CMakeLists.txt).

**Comment by cheshirekow** [comment]
Awesome, thanks for the report and the example. I'll see if I can spot the issue.

**Comment by kdheepak** [comment]
No problem! I took a look but didn't dig into it further. Excited to have a cmake formatter in Python! So let me know if I can help in any way.

**Comment by cheshirekow** [comment]
Ah, yes, the problem is case. I always use lowercase for builtin statements and forgot that you can use either. I'll roll a fix out soon but here's a patch that will allow it to work for your listfile. Note that the design of `cmake-format` doesn't allow for things like:

```
# ------------------------------------------------------------- 
# Setup compiler options and configurations
# -------------------------------------------------------------
```

As it will try to reflow the comment. I'm currently reconsidering this design decision and will likely change it so that it limits it's reflow logic. Perhaps only to overlong comments or perhaps using some options to change how aggressive/smart it is. In any case, `cmake-format` as it currently stands might not be right for your project, but keep an eye on it and I'll roll that reflow change out soon :).

Patch:
```
diff --git a/cmake_format/parser.py b/cmake_format/parser.py
index 5e04d78..95d75bb 100644
--- a/cmake_format/parser.py
+++ b/cmake_format/parser.py
@@ -347,71 +347,73 @@ def construct_fst(token_seqs):
     elif tok_seq.type == WHITESPACE:
       block_stack[-1].children.append(Whitespace(tok_seq))
     elif tok_seq.type == STATEMENT:
-      if tok_seq.tokens[0].content == 'if':
+      if tok_seq.tokens[0].content.lower() == 'if':
         block = Block(IF_BLOCK)
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(block)
         block.children.append(stmt)
         block_stack.append(block)
         block_stack.append(stmt)
-      elif tok_seq.tokens[0].content in ['elseif', 'else']:
+      elif tok_seq.tokens[0].content.lower() in ['elseif', 'else']:
         assert block_stack and block_stack.pop(-1)
         assert block_stack and block_stack[-1].block_type == IF_BLOCK
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(stmt)
         block_stack.append(stmt)
-      elif tok_seq.tokens[0].content == 'endif':
+      elif tok_seq.tokens[0].content.lower() == 'endif':
         assert block_stack and block_stack.pop(-1)
-        assert block_stack and block_stack[-1].block_type == IF_BLOCK
+        assert block_stack and block_stack[-1].block_type == IF_BLOCK, (
+            "Expected if() at line {}"
+            .format(tok_seq.tokens[0].line))
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(stmt)
         block_stack.pop(-1)
-      elif tok_seq.tokens[0].content == 'while':
+      elif tok_seq.tokens[0].content.lower() == 'while':
         block = Block(WHILE)
         stmt = Statement(tok_seq)
         block.children.append(stmt)
         block_stack.append(block)
         block_stack.append(stmt)
-      elif tok_seq.tokens[0].content == 'endwhile':
+      elif tok_seq.tokens[0].content.lower() == 'endwhile':
         assert block_stack and block_stack.pop(-1)
         assert block_stack and block_stack[-1].block_type == WHILE
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(stmt)
         block_stack.pop(-1)
-      elif tok_seq.tokens[0].content == 'foreach':
+      elif tok_seq.tokens[0].content.lower() == 'foreach':
         block = Block(FOREACH)
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(block)
         block.children.append(stmt)
         block_stack.append(block)
         block_stack.append(stmt)
-      elif tok_seq.tokens[0].content == 'endforeach':
+      elif tok_seq.tokens[0].content.lower() == 'endforeach':
         assert block_stack and block_stack.pop(-1)
         assert block_stack and block_stack[-1].block_type == FOREACH
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(stmt)
         block_stack.pop(-1)
-      elif tok_seq.tokens[0].content == 'function':
+      elif tok_seq.tokens[0].content.lower() == 'function':
         block = Block(FUNCTION_DEF)
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(block)
         block.children.append(stmt)
         block_stack.append(block)
         block_stack.append(stmt)
-      elif tok_seq.tokens[0].content == 'endfunction':
+      elif tok_seq.tokens[0].content.lower() == 'endfunction':
         assert block_stack and block_stack.pop(-1)
         assert block_stack and block_stack[-1].block_type == FUNCTION_DEF
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(stmt)
         block_stack.pop(-1)
-      elif tok_seq.tokens[0].content == 'macro':
+      elif tok_seq.tokens[0].content.lower() == 'macro':
         block = Block(MACRO_DEF)
         stmt = Statement(tok_seq)
         block_stack[-1].children.append(block)
         block.children.append(stmt)
         block_stack.append(block)
         block_stack.append(stmt)
-      elif tok_seq.tokens[0].content == 'endmacro':
+      elif tok_seq.tokens[0].content.lower() == 'endmacro':
         assert block_stack and block_stack.pop(-1)
         assert block_stack and block_stack[-1].block_type == MACRO_DEF
         stmt = Statement(tok_seq)

```

**Comment by kdheepak** [comment]
Thanks for the detailed comment! I'll be keeping an eye out on this project for changes.
