### ISSUE TITLE
Crashes on specific file during pre-commit hook

### ISSUE THREAD

**Issue by Skylion007** [cheshirekow/cmake_format#220]
```
// Copyright (c) Facebook, Inc. and its affiliates.
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

#define SCENE_DATASETS "${SCENE_DATASETS}"
#define TEST_ASSETS "${TEST_ASSETS}"

#define FILE_THAT_EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/IOTest.cpp"
```

```
WARNING __main__.py:530: While processing src/tests/configure.h.cmake
ERROR __main__.py:638: Unexpected UNQUOTED_LITERAL token at 1:0
Traceback (most recent call last):
  File "/private/home/agokaslan/.cache/pre-commit/repoo8nb42vl/py_env-python3/lib/python3.6/site-packages/cmakelang/format/__main__.py", line 633, in main
    return inner_main()
  File "/private/home/agokaslan/.cache/pre-commit/repoo8nb42vl/py_env-python3/lib/python3.6/site-packages/cmakelang/format/__main__.py", line 616, in inner_main
    onefile_main(infile_path, args, argparse_dict)
  File "/private/home/agokaslan/.cache/pre-commit/repoo8nb42vl/py_env-python3/lib/python3.6/site-packages/cmakelang/format/__main__.py", line 526, in onefile_main
    outtext, reflow_valid = process_file(cfg, intext, args.dump)
  File "/private/home/agokaslan/.cache/pre-commit/repoo8nb42vl/py_env-python3/lib/python3.6/site-packages/cmakelang/format/__main__.py", line 158, in process_file
    parse_tree = parse.parse(tokens, ctx)
  File "/private/home/agokaslan/.cache/pre-commit/repoo8nb42vl/py_env-python3/lib/python3.6/site-packages/cmakelang/parse/__init__.py", line 68, in parse
    return BodyNode.consume(ctx, tokens)
  File "/private/home/agokaslan/.cache/pre-commit/repoo8nb42vl/py_env-python3/lib/python3.6/site-packages/cmakelang/parse/body_nodes.py", line 78, in consume
    tokens[0].begin.line, tokens[0].begin.col))
cmakelang.common.InternalError
```
I am trying to use cmake_format a pre-commit hook per your other repo, but when scanning the file posted above, it crashes. You should adjust the commit hook or the cmake_format accordingly.

**Comment by cheshirekow** [comment]
This is not a valid cmake file. This looks like a c header which is configured by cmake. Usually I see people name this with a `.h.in` extension, rather than ` .h.cmake` extension... but in any case, I would not expect `cmake-format` to do anything but exit with an error code in this case. It looks to me like correct behavior.

**Comment by Skylion007** [comment]
@cheshirekow You may still want to tighten up the pre-commit hook a bit though. 

A Brief [Github Code Search](https://github.com/search?q=filename%3A*.h.cmake&type=Code) reveals about 74K files that use the .h.cmake extension. I doubt very many of them are actually cmake files.

**Comment by cheshirekow** [comment]
> tighten up the pre-commit hook a bit though.

What specifically are you suggesting?

**Comment by Skylion007** [comment]
Maybe add a `[^.]` to the include regex so it won't accept anything would accept `configure.cmake` as valid, but not `configure.h.cmake` in the default pre-commit hook include.

**Comment by cheshirekow** [comment]
Which regex are you referring to?

**Comment by Skylion007** [comment]
@cheshirekow This one: https://github.com/iconmaster5326/cmake-format-pre-commit-hook/blob/07978b29a9a9fbe98fcd605a74d970a1ce86483f/.pre-commit-hooks.yaml#L6

**Comment by cheshirekow** [comment]
That's not my repository.

**Comment by Skylion007** [comment]
Oh whoops, yeah I see you are using the types in yours: https://github.com/cheshirekow/cmake-format-precommit/blob/master/.pre-commit-hooks.yaml#L4 so it's identify problem, not yours. In which, case just improving the error message should be sufficient.

**Comment by CAM-Gerlach** [comment]
FYI @Skylion007 , Github code search can be a bit misleading, as the `filename` field unfortunately considers neither wildcards nor (unlike the `extension` field) exact matches. Of the files whose last extension component is `in`, [676 000](https://github.com/search?q=filename%3Ah.in+extension%3Ain&type=Code) contain`h.in`, [276 000](https://github.com/search?q=filename%3Acmake+extension%3Ain&type=Code) contain `cmake`, while there are [15 500](https://github.com/search?q=filename%3Ah.cmake.in+extension%3Ain&type=Code) contain `h.cmake.in`.

By contrast, of the files with the `cmake` extension, [50 000](https://github.com/search?q=filename%3Ah.cmake+extension%3Acmake&type=Code) have the `h.cmake` in the filename, [12 300](https://github.com/search?q=filename%3Ah.cmake+extension%3Acmake&type=Code) have `in` somewhere in the filename (but the vast majority of those spot-checked aren't `in.cmake`, but rather have it as part of the filename), and only [2279](https://github.com/search?q=filename%3Ah.in.cmake+extension%3Acmake&type=Code) have `h.in.cmake`.

As to the implications for this use case, that's not for me to determine; just wanted to clear up that potential confusion.
