### ISSUE TITLE
Error when trying to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by lucascoelhof** [cheshirekow/cmake_format#238]
I followed the instructions on how to install and I've got this as result:
```
lucas@lucas-vm:~$  pip install cmakelang
Collecting cmakelang
  Downloading https://files.pythonhosted.org/packages/74/c0/75d4806cf21dcb4198e9fba02f4d2fa61c8db919b7db788862d9cd5f4433/cmakelang-0.6.13.tar.gz (123kB)
    100% |████████████████████████████████| 133kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xm_7x1/cmakelang/setup.py", line 16, in <module>
        with io.open("cmakelang/doc/README.rst", encoding="utf-8") as infile:
    IOError: [Errno 2] No such file or directory: 'cmakelang/doc/README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xm_7x1/cmakelang/
```
Any ideas on how to install this package?

**Comment by lucascoelhof** [comment]
```pip install cmake_format``` also fails with the following output:
```
lucas@lucas-vm:~$ pip install cmake_format
Collecting cmake_format
  Using cached https://files.pythonhosted.org/packages/5d/3e/f1a7388ce2528b69fbfce9691e5c97f1b2b2b83c25711e0627c3e8f99e58/cmake-format-0.6.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lNegKe/cmake-format/setup.py", line 7, in <module>
        with io.open("cmakelang/__init__.py", encoding="utf-8") as infile:
    IOError: [Errno 2] No such file or directory: 'cmakelang/__init__.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lNegKe/cmake-format/
```

**Comment by cheshirekow** [comment]
Have you configured pip to not install wheels for some reason? It appears that the installation is trying to install from the source package, and maybe a file is missing there. The wheel should install OK though.

**Comment by FranciscoMoretti** [comment]
Just in case this gives any additional info to understand this problem. I had an issue with the same output.
When I tried to install with wheels I got the following message:
```
ERROR: cmakelang-0.6.13-py3-none-any.whl is not a supported wheel on this platform.
```

Was able to avoid the issue by installing with pip3.
