### ISSUE TITLE
Python2 pip installation fails

### ISSUE THREAD

**Issue by sweetgiorni** [cheshirekow/cmake_format#248]
Python 2.7.5
pip 20.3.4 from /usr/lib/python2.7/site-packages/pip (python 2.7)
setuptools 44.1.1 from /usr/lib/python2.7/site-packages (Python 2.7)

```Shell
➜  cmake_format git:(master) ✗ pip install cmakelang
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting cmakelang
  Using cached cmakelang-0.6.13.tar.gz (123 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kHmpI1/cmakelang/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kHmpI1/cmakelang/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ZvpqHF
         cwd: /tmp/pip-install-kHmpI1/cmakelang/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kHmpI1/cmakelang/setup.py", line 16, in <module>
        with io.open("cmakelang/doc/README.rst", encoding="utf-8") as infile:
    IOError: [Errno 2] No such file or directory: 'cmakelang/doc/README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Downloading `cmakelang-0.6.13.tar.gz` and exctracting it shows that the folder 'cmakelang' is indeed missing. I tried installing through pip straight from GitHub but that resulted in a different error:
```Shell
➜  cmake_format git:(master) ✗ pip install git+https://github.com/cheshirekow/cmake_format.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting git+https://github.com/cheshirekow/cmake_format.git
  Cloning https://github.com/cheshirekow/cmake_format.git to /tmp/pip-req-build-Bl9bTM
  Running command git clone -q https://github.com/cheshirekow/cmake_format.git /tmp/pip-req-build-Bl9bTM
ERROR: More than one .egg-info directory found in /tmp/pip-pip-egg-info-RkAsMH
```
The only way I could get it to install correctly was to clone the Git repo manually and run `python setup.py install` .

**Comment by sweetgiorni** [comment]
Derp, this is a duplicate. #234
