### ISSUE TITLE
Cannot invoke cmake-format with Python 3 on Windows

### ISSUE THREAD

**Issue by joeced** [cheshirekow/cmake_format#25]
When I try to invoke ``cmake-format`` with Python 3 from a command prompt in Windows, I get the following error.

```
c:\>cmake-format
Traceback (most recent call last):
  File "C:\Python36\Scripts\cmake-format-script.py", line 11, in <module>
    load_entry_point('cmake-format==0.3.2', 'console_scripts', 'cmake-format')()
  File "c:\python36\lib\site-packages\cmake_format\__main__.py", line 184, in main
    for key, value in configuration.Configuration().as_dict().iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

In Python 3 the `iteritems` does not exist for `dict`. Use `items` instead.

**Comment by joeced** [comment]
Pull request #20 solves this
