### ISSUE TITLE
cmake-format exception when files are already formatted

### ISSUE THREAD

**Issue by armandas** [cheshirekow/cmake_format#262]
I am getting the following traceback when checking the formatting of already-formatted files:

```
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/cmake_format/__main__.py", line 570, in main
    return inner_main()
  File "/usr/local/lib/python3.8/site-packages/cmake_format/__main__.py", line 514, in inner_main
    outtext, reflow_valid = process_file(cfg, intext, args.dump)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/__main__.py", line 131, in process_file
    box_tree = formatter.layout_tree(parse_tree, config, first_token=first_token)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 1621, in layout_tree
    root_box.reflow(stack_context, Cursor(0, 0))
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 1437, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 1463, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 731, in reflow
    return super(StatementNode, self).reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 817, in _reflow
    cursor = child.reflow(stack_context, cursor, passno)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 1263, in _reflow
    cursor = child.reflow(stack_context, cursor, passno)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 1127, in _reflow
    cursor = child.reflow(stack_context, input_cursor, passno)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 617, in _reflow
    cursor = child.reflow(stack_context, cursor + (0, 1), passno)
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 491, in reflow
    outcursor = self._reflow(
  File "/usr/local/lib/python3.8/site-packages/cmake_format/formatter.py", line 1542, in _reflow
    self._colextent = cursor[1] + max(len(line) for line in lines)
ValueError: max() arg is an empty sequence
```

cmake-format version: 0.6.10 (using the official docker image), also tried 0.6.13

cmake-format is run as below:

```
find -type f -name "*.cmake" | xargs cmake-format -i
```

**Comment by armandas** [comment]
It looks like the issue is caused by using bracket comments. I have updated the description.
