### ISSUE TITLE
default codec used to read long_description can't decode utf8 in README.rst

### ISSUE THREAD

**Issue by joeced** [cheshirekow/cmake_format#3]
Looks like a very promising project! I tried to install using ``pip install cmake_format``, but got this error message:

```
(.venv) c:\home\simulator\dchipset>pip install --user cmake_format
Collecting cmake_format
  Downloading <local pypi proxy path>/cmake_format-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jce\AppData\Local\Temp\pip-build-1yx3c08l\cmake-format\setup.py", line 4, in <module>
        long_description = infile.read()
      File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3710: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jce\AppData\Local\Temp\pip-build-1yx3c08l\cmake-format\
```

Maybe it's because the ``README.rst`` file is a symbolic link, which is not really supported on Windows.

**Comment by cheshirekow** [comment]
Hm.. interesting. It might be symbolic link but based on the location it looks more like there might be some UTF embedded in the long description. I'll check it out when I get a chance.

**Comment by cheshirekow** [comment]
Yeah, it seems to be a problem with the utf8 in `README.rst`. `0x8d` is found in this nugget:

```
    # This part of the comment should
    # be formatted
    # but...
    # cmake-format: off
    # This bunny should remain untouched:
    # . 　 ＿　∩
    # 　　ﾚﾍヽ| |
    # 　　　 (・ｘ・)
    # 　　 c( uu}
    # cmake-format: on
    #          while this part should
    #          be formatted again
```
I don't have a windows computer to test on, but if you're willing could you try this patch and let me know? If not, I'll include this change in v0.3 that I'll push to pypi soon so you can try to pip install when that is up.

```
diff --git a/clangdoc/pypi/setup.py b/clangdoc/pypi/setup.py
index 9ff62e5..fb9b0bf 100644
--- a/clangdoc/pypi/setup.py
+++ b/clangdoc/pypi/setup.py
@@ -1,6 +1,7 @@
+import io
 from setuptools import setup
 
-with open('README.rst') as infile:
+with io.open('README.rst', encoding='utf8') as infile:
   long_description = infile.read()
 
 setup(
```
