### ISSUE TITLE
Add NumPy as Required Package

### ISSUE THREAD

**Issue by sanssecours** [cheshirekow/cmake_format#53]
👋 Hi,

thank you for providing this very useful utility.

The last version of `cmake-format` (`0.4.0`) [requires the package NumPy](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/formatter.py#L10). However, [`setup.py` does not list `numpy` as dependency](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/pypi/setup.py#L37-L39), as far as I can tell. This causes `cmake-format` to fail, if you do not install `numpy` too. For example, after I upgraded to the latest version of `cmake-format`, the command

```sh
cmake-format --version
```

failed printing the following error message:

```
Traceback (most recent call last):
  File "/Users/rene/.pyenv/versions/3.7.0/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format==0.4.0', 'console_scripts', 'cmake-format')()
  File "/Users/rene/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/rene/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/Users/rene/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/Users/rene/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/rene/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cmake_format/__main__.py", line 29, in <module>
    from cmake_format import formatter
  File "/Users/rene/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cmake_format/formatter.py", line 10, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

.

**Comment by cheshirekow** [comment]
Ah, yeah, definitely forgot to update setup.py
