### ISSUE TITLE
Invalid CMake syntax crashes cmake format

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#57]
If I run cmake-format on something like

```
cmake_minimum_required(VERSION 3.9)

project(test)

sdfsdfsd
```

There will be error

```
While processing CMakeLists.txt
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format==0.4.0', 'console_scripts', 'cmake-format')()
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 336, in main
    process_file(cfg, infile, outfile, args.dump)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 58, in process_file
    parse_tree = parser.parse(tokens, config.fn_spec)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 600, in parse
    return consume_body(tokens, cmdspec)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 579, in consume_body
    subtree = consume_statement(tokens, cmdspec)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 451, in consume_statement
    if tokens[0].type != lexer.TokenType.LEFT_PAREN:
IndexError: list index out of range
```

and here is another example

```
cmake_minimum_required(VERSION 3.9)

project(test
```

```
While processing CMakeLists.txt
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format==0.4.0', 'console_scripts', 'cmake-format')()
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 336, in main
    process_file(cfg, infile, outfile, args.dump)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 58, in process_file
    parse_tree = parser.parse(tokens, config.fn_spec)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 600, in parse
    return consume_body(tokens, cmdspec)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 579, in consume_body
    subtree = consume_statement(tokens, cmdspec)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 464, in consume_statement
    consume_arguments(subtree, tokens, cmdspec.get(fnname, None), [])
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parser.py", line 428, in consume_arguments
    .format(node.get_location()))
ValueError: Token stream expired while parsing statement arguments starting at 3:8
```

It would be nice if cmake-format will just simply do nothing and return if the syntax is invalid. On top of that perhaps show an error message.

The main reason I am asking this is because for the sublime cmake format plugin I am maintaining https://github.com/jasjuang/sublime_cmake_format there is a format on save functionality that is intended for speeding up development, but the problem is if the developer is typing something halfway and habitually click `ctrl+s` it will crash because the syntax is invalid. 

If we reference clang-format, even if we type in some gibberish that can't be compiled clang-format will still attempt to format it into something instead of crashing it, so there's no problem running it with format on save.

**Comment by cheshirekow** [comment]
I'm inclined to stick with unix philosophy here. If cmake format can't parse the listfile, it can't format it. Since formatting a file is it's purpose it should exit with nonzero status code in this situation. I feel pretty strongly that cmake-format should not fail silently. You could always wrap the formatter in a shell script with `|| true` or (as you've done in your plugin) ignore the exit code. 

I *would* like to improve error messaging to better indicate *what* is wrong with the input (rather than opaque assertion messages etc. The one you noted though is pretty clear. The statement starting at line `3`, column `8` is not terminated. 

Taking a look at your plugin, I don't see how cmake-format exiting with nonzero would crash sublime. This looks like it would "do nothing" in that case... which seems to be what you want.

```
        if error:
            # We don't want to do anything by default.
            # If the error message tells us it is doing that, truncate it.
            default_message = "cmake format is wrong"
            msg = error.decode("utf-8")
            if msg.strip().endswith(default_message):
                msg = msg[:-len(default_message)-1]
            sublime.error_message("CMake format: " + msg)
            # Don't do anything.
            return
```

One thing `cmake-format` *could* do is format as much of the parse tree as it's able to construct, but if there are syntax errors in the file the chances are it's not going to make good decisions.

**Comment by mnijhuis-tos** [comment]
The examples above clearly have invalid syntax. A simple file with `if(FOO)` also crashes cmake-format: Although the line itself is correct, the syntax of the entire file isn't because the `endif()` is missing.

A file with only `endif()` does not crash cmake-format, though.
