### ISSUE TITLE
Keyword + long comment + long argument asserts

### ISSUE THREAD

**Issue by siedentop** [cheshirekow/cmake_format#82]
Here is a bug which I see. It only appears if one of the 'COMPONENTS' arguments
is too long.

Minimized example:
```
find_package(package REQUIRED
             COMPONENTS # --------------------------------------
                        # @TODO: This has to be filled manually
                        # --------------------------------------
                        this_is_a_really_long_word_foo)


```

Error:
```commandline
(venv) ❯ cmake-format  regression1.cmake
While processing regression1.cmake
Traceback (most recent call last):
  File "/path/to/src/cmake_format/venv/bin/cmake-format", line 11, in <module>
    load_entry_point('cmake-format', 'console_scripts', 'cmake-format')()
  File "/path/to/src/cmake_format/cmake_format/__main__.py", line 336, in main
    process_file(cfg, infile, outfile, args.dump)
  File "/path/to/src/cmake_format/cmake_format/__main__.py", line 67, in process_file
    text = formatter.write_tree(box_tree, config, infile_content)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 1280, in write_tree
    root_box.write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 274, in _write
    child.write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 625, in _write
    super(StatementNode, self)._write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 274, in _write
    child.write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 274, in _write
    child.write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 381, in _write
    ctx.outfile.write_at(self.position, spelling)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 1213, in write_at
    self.assert_lt(cursor)
  File "/path/to/src/cmake_format/cmake_format/formatter.py", line 1205, in assert_lt
    self.getvalue().encode('utf-8', errors='replace'))
AssertionError: self._cursor=(4,53), write_at=(3, 4):
find_package(
  package REQUIRED
  COMPONENTS # --------------------------------------
             # @TODO: This has to be filled manually
             # --------------------------------------
```

Here is the layout tree:
```commandline
(venv) ❯ cmake-format --dump=layout regression1.cmake
└─ BODY,HPACK(0) p(0,0) ce:53
    └─ STATEMENT,KWNVPACK(2) p(0,0) ce:53
        ├─ FUNNAME,HPACK(0) p(0,0) ce:12
        ├─ LPAREN,HPACK(0) p(0,12) ce:13
        ├─ ARGUMENT,HPACK(0) p(1,2) ce:9
        ├─ ARGUMENT,HPACK(0) p(1,10) ce:18
        ├─ KWARGGROUP,KWNVPACK(2) p(2,2) ce:53
        │   ├─ KEYWORD,VPACK(1) p(2,2) ce:53
        │   │   └─ COMMENT,HPACK(0) p(2,13) ce:53
        │   └─ ARGUMENT,HPACK(0) p(3,4) ce:34
        └─ RPAREN,HPACK(0) p(3,34) ce:35
```

Here is the parse tree:
```commandline
(venv) ❯ cmake-format --dump=parse regression1.cmake
└─ BODY: 1:0
    ├─ STATEMENT: 1:0
    │   ├─ FUNNAME: 1:0
    │   │   └─ Token(type=WORD, content=u'find_package', line=1, col=0)
    │   ├─ LPAREN: 1:12
    │   │   └─ Token(type=LEFT_PAREN, content=u'(', line=1, col=12)
    │   ├─ ARGGROUP: 1:13
    │   │   ├─ ARGUMENT: 1:13
    │   │   │   └─ Token(type=WORD, content=u'package', line=1, col=13)
    │   │   ├─ Token(type=WHITESPACE, content=u' ', line=1, col=20)
    │   │   ├─ ARGUMENT: 1:21
    │   │   │   └─ Token(type=WORD, content=u'REQUIRED', line=1, col=21)
    │   │   ├─ Token(type=NEWLINE, content=u'\n', line=1, col=29)
    │   │   ├─ Token(type=WHITESPACE, content=u'             ', line=2, col=0)
    │   │   └─ KWARGGROUP: 2:13
    │   │       ├─ KEYWORD: 2:13
    │   │       │   ├─ Token(type=WORD, content=u'COMPONENTS', line=2, col=13)
    │   │       │   ├─ Token(type=WHITESPACE, content=u' ', line=2, col=23)
    │   │       │   └─ COMMENT: 2:24
    │   │       │       ├─ Token(type=COMMENT, content=u'# --------------------------------------', line=2, col=24)
    │   │       │       ├─ Token(type=NEWLINE, content=u'\n', line=2, col=64)
    │   │       │       ├─ Token(type=WHITESPACE, content=u'                        ', line=3, col=0)
    │   │       │       ├─ Token(type=COMMENT, content=u'# @TODO: This has to be filled manually', line=3, col=24)
    │   │       │       ├─ Token(type=NEWLINE, content=u'\n', line=3, col=63)
    │   │       │       ├─ Token(type=WHITESPACE, content=u'                        ', line=4, col=0)
    │   │       │       └─ Token(type=COMMENT, content=u'# --------------------------------------', line=4, col=24)
    │   │       ├─ Token(type=NEWLINE, content=u'\n', line=4, col=64)
    │   │       ├─ Token(type=WHITESPACE, content=u'                        ', line=5, col=0)
    │   │       └─ ARGUMENT: 5:24
    │   │           └─ Token(type=WORD, content=u'this_is_a_really_long_word_foo', line=5, col=24)
    │   └─ RPAREN: 5:54
    │       └─ Token(type=RIGHT_PAREN, content=u')', line=5, col=54)
    └─ WHITESPACE: 5:55
        └─ Token(type=NEWLINE, content=u'\n', line=5, col=55)
```

* Version used: 161a19b9b7db3dbbe35ac8db92b05d74469f9682
* Python 2.7 in virtualenv
* On macOS High Sierra

**Comment by cheshirekow** [comment]
With other changes made in version `0.4.4` this bug no longer appears to be present. I suspect its actually the same as #81 due to the comment. Should be pushed soon.

**Comment by siedentop** [comment]
Hi @cheshirekow , 

 thank you for looking at my multiple reports! And, I concur, it looks very similar to #81.

Unfortunately using version `0.4.4` this issue still occurs for me.

The machine configuration is as above, except `venv2` which is a new virtual environment where I installed the current master (i.e. 0.4.4).

Can I help in any way? Please let me know if you need more information.

```
(venv2) ❯ cmake-format --version && cat minimal.cmake && cmake-format minimal.cmake
0.4.4
find_package(package REQUIRED
             COMPONENTS # --------------------------------------
                        # @TODO: This has to be filled manually
                        # --------------------------------------
                        this_is_a_really_long_word_foo)

While processing minimal.cmake
Traceback (most recent call last):
  File "/Users/siedenc/src/cmake_format/venv2/bin/cmake-format", line 11, in <module>
    sys.exit(main())
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/__main__.py", line 421, in main
    process_file(cfg, infile, outfile, args.dump)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/__main__.py", line 132, in process_file
    text = formatter.write_tree(box_tree, config, infile_content)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 1282, in write_tree
    root_box.write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 274, in _write
    child.write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 625, in _write
    super(StatementNode, self)._write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 274, in _write
    child.write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 274, in _write
    child.write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 277, in write
    self._write(config, ctx)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 382, in _write
    ctx.outfile.write_at(self.position, spelling)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 1215, in write_at
    self.assert_lt(cursor)
  File "/Users/siedenc/src/cmake_format/venv2/lib/python2.7/site-packages/cmake_format/formatter.py", line 1207, in assert_lt
    self.getvalue().encode('utf-8', errors='replace'))
AssertionError: self._cursor=(4,53), write_at=(3, 4):
find_package(
  package REQUIRED
  COMPONENTS # --------------------------------------
             # @TODO: This has to be filled manually
             # --------------------------------------
```

**Comment by cheshirekow** [comment]
Ah got it. Indeed testing now I'm reproducing the problem. Maybe I had a copy-paste error or something when I wasn't able to reproduce before. Will update as I dig in.

**Comment by cheshirekow** [comment]
I think I got it for real this time. Please let me know if you still encounter this problem (or any others).

**Comment by cheshirekow** [comment]
Ah yeah, I had some issues with unstable formatting before. Please do open an issue with your test case when you get a chance.
