### ISSUE TITLE
installing cmake-format with pip3 missing yaml dependency

### ISSUE THREAD

**Issue by gocarlos** [cheshirekow/cmake_format#99]
when doing `sudo pip3 install cmake-format` on base ubuntu:18.04 docker image the package yaml is not installed -> my script (cmake-format-lint-check.sh) crashes then due to missing yaml

```
path_to_cmake_format :/usr/local/bin/cmake-format
cmake-format was found, going to format your cmake scripts...
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cmake_format/__main__.py", line 386, in main
    config_dict = get_config(infile_path, args.config_file)
  File "/usr/local/lib/python3.6/dist-packages/cmake_format/__main__.py", line 215, in get_config
    import yaml
ModuleNotFoundError: No module named 'yaml'
./scripts/cmake-format-lint-check.sh: line 49: git: command not found
./scripts/cmake-format-lint-check.sh: line 63: git: command not found
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cmake_format/__main__.py", line 386, in main
    config_dict = get_config(infile_path, args.config_file)
  File "/usr/local/lib/python3.6/dist-packages/cmake_format/__main__.py", line 215, in get_config
    import yaml
ModuleNotFoundError: No module named 'yaml'
./scripts/cmake-format-lint-check.sh: line 49: git: command not found
./scripts/cmake-format-lint-check.sh: line 63: git: command not found
```

**Comment by cheshirekow** [comment]
Yaml isn't required to use `cmake-format` so it isn't a required package dependency. It is an optional dependency through. Try `pip install cmake_format[yaml]`.

**Comment by cheshirekow** [comment]
Did `cmake_format[yaml]` work for you?

**Comment by cheshirekow** [comment]
ping again @gocarlos does it work if you specify the pip optional?

**Comment by cheshirekow** [comment]
I'm going to close this issue for now. Please feel free to comment if you have any more to add. If you're still having trouble I'm happy to re-open and discuss further.
